### ISSUE TITLE
DOMParser is not defined w/ SSR & NextJS

### ISSUE THREAD

**Issue by gregegan** [odedglas/linear-gradient-parser#8]
Hey all - it looks like while using the `react-linear-gradient-picker` repo, that it has a dependency on this repo `linear-gradient-parser`. This fails when trying to serverside render.

Can you add a polyfill for DOMParser? Or is there a better solution for me to use this with ssr?

https://github.com/odedglas/react-linear-gradient-picker

https://developer.mozilla.org/en-US/docs/Web/API/DOMParser

![image](https://user-images.githubusercontent.com/6665100/98595702-2e72b500-228b-11eb-8f2f-1107e4d6dc27.png)

**Comment by gregegan** [comment]
FYI - Dynamically importing it and disabling SSR is a workaround.

```
const GradientPicker = dynamic(() =>
    import('./GradientPicker'),
  { ssr: false });
```

https://nextjs.org/docs/advanced-features/dynamic-import

**Comment by odeadglaz** [comment]
Hey, totally valid point.

As you said, dynamic importing should resolve this case, tho I will add isomorphic support for this package.
Thanks for you're reporting.

**Comment by gregegan** [comment]
Thanks!

**Comment by odeadglaz** [comment]
Sorry for the late handling, I moved DOM parser instantiation to actual usage, it shouldn't happen any longer.
